/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.TransaksiController;
import model.TransaksiHeader;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author yiachmad
 */
public class FormCariTransaksi extends javax.swing.JFrame {
    private JTextField tfNoInv;
    private JButton btnEdit, btnHapus;
    
    /**
     * Creates new form FormCariTransaksi
     */
    public FormCariTransaksi() {
        setTitle("Cari / Edit / Hapus Transaksi");
        setSize(350, 120);
        setLayout(new FlowLayout());
        setLocationRelativeTo(null);

        tfNoInv = new JTextField(15);
        btnEdit = new JButton("Edit");
        btnHapus = new JButton("Hapus");

        add(new JLabel("No Invoice:"));
        add(tfNoInv);
        add(btnEdit);
        add(btnHapus);

        btnEdit.addActionListener(e -> {
            String noInv = tfNoInv.getText();
            try {
                TransaksiHeader header = TransaksiController.getTransaksiByNoInv(noInv);
                if (header == null) {
                    JOptionPane.showMessageDialog(this, "Transaksi tidak ditemukan");
                } else {
                    FormTransaksi form = new FormTransaksi();
                    form.loadData(header); // mode edit
                    form.setVisible(true);
                    dispose();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Gagal memuat transaksi");
            }
        });

        btnHapus.addActionListener(e -> {
            String noInv = tfNoInv.getText();
            int confirm = JOptionPane.showConfirmDialog(this,
                "Yakin ingin menghapus transaksi " + noInv + "?", "Konfirmasi",
                JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    TransaksiController.deleteTransaksi(noInv);
                    JOptionPane.showMessageDialog(this, "Transaksi berhasil dihapus");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus transaksi: " + ex.getMessage());
                }
            }
        });

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
